export const hinduWisdom = [
  { quote: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन', translation: 'You have the right to perform your actions, but not to the fruits of action', source: 'Bhagavad Gita 2.47', relevance: 'Focus on studying without attachment to results. Your dedication to NEET preparation is your dharma.' },
  { quote: 'श्रद्धावान् लभते ज्ञानं तत्परः संयतेन्द्रियः', translation: 'The faithful one, devoted to knowledge and controlling the senses, attains wisdom', source: 'Bhagavad Gita 4.39', relevance: 'Faith in your abilities and controlled focus on studies will lead you to medical knowledge and NEET success.' },
  { quote: 'उद्यमेन हि सिध्यन्ति कार्याणि न मनोरथैः', translation: 'Success comes through effort, not through wishful thinking', source: 'Hitopadesh', relevance: 'NEET success requires consistent daily effort in solving questions and studying, not just dreaming about becoming a doctor.' },
  { quote: 'विद्या ददाति विनयं विनयाद्याति पात्रताम्', translation: 'Knowledge gives humility, from humility comes worthiness', source: 'Hitopadesh', relevance: 'As you gain medical knowledge through NEET preparation, stay humble and worthy of serving patients as a future doctor.' },
  { quote: 'सत्यमेव जयते नानृतं', translation: 'Truth alone triumphs, not falsehood', source: 'Mundaka Upanishad', relevance: 'Be truthful in your preparation - honestly assess your weaknesses and work on them. Truth in self-evaluation leads to NEET success.' },
  { quote: 'आत्मानं विद्धि', translation: 'Know thyself', source: 'Upanishads', relevance: 'Understand your learning style, peak study hours, and strengths. Self-knowledge is key to optimizing your NEET preparation strategy.' },
  { quote: 'धैर्यं सर्वत्र साधनम्', translation: 'Patience is the means to everything', source: 'Sanskrit Proverb', relevance: 'NEET preparation is a long journey. Maintain patience with difficult concepts and trust the process of gradual improvement.' },
  { quote: 'योगः कर्मसु कौशलम्', translation: 'Yoga is skill in action', source: 'Bhagavad Gita 2.50', relevance: 'Develop skillful study techniques and efficient problem-solving methods for NEET preparation.' },
  { quote: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते', translation: 'Nothing in this world is as purifying as knowledge', source: 'Bhagavad Gita 4.38', relevance: 'Medical knowledge you gain through NEET preparation will purify your mind and help you serve humanity.' },
  { quote: 'तत्त्वं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति', translation: 'Whoever offers Me with devotion a leaf, flower, fruit or water, I accept it', source: 'Bhagavad Gita 9.26', relevance: 'Offer your studies as devotion. Every question solved with dedication is an offering to the divine.' },
  { quote: 'तमसो मा ज्योतिर्गमय', translation: 'Lead me from darkness to light', source: 'Brihadaranyaka Upanishad', relevance: 'Move from ignorance to knowledge through NEET preparation.' },
  { quote: 'असतो मा सद्गमय', translation: 'Lead me from untruth to truth', source: 'Brihadaranyaka Upanishad', relevance: 'Seek truth in your studies and honest self-assessment.' },
  { quote: 'मृत्योर्मा अमृतं गमय', translation: 'Lead me from death to immortality', source: 'Brihadaranyaka Upanishad', relevance: 'Transform from failure to eternal success through dedication.' },
  { quote: 'वसुधैव कुटुम्बकम्', translation: 'The world is one family', source: 'Maha Upanishad', relevance: 'As a future doctor, you will serve the entire human family.' },
  { quote: 'अहिंसा परमो धर्मः', translation: 'Non-violence is the highest virtue', source: 'Mahabharata', relevance: 'Medicine is the practice of healing, embodying the principle of ahimsa.' },
  { quote: 'विद्या विनयेन शोभते', translation: 'Knowledge shines with humility', source: 'Sanskrit Proverb', relevance: 'Let your medical knowledge be adorned with humility and compassion.' },
  { quote: 'स्वाध्याय प्रवचनाभ्यां न प्रमदितव्यम्', translation: 'Never be negligent in study and teaching', source: 'Taittiriya Upanishad', relevance: 'Be consistent in your NEET preparation and share knowledge with others.' },
  { quote: 'आचार्य देवो भव', translation: 'Let the teacher be your god', source: 'Taittiriya Upanishad', relevance: 'Respect your teachers and mentors in your NEET journey.' },
  { quote: 'मातृ देवो भव', translation: 'Let mother be your god', source: 'Taittiriya Upanishad', relevance: 'Honor your mother who supports your medical dreams.' },
  { quote: 'पितृ देवो भव', translation: 'Let father be your god', source: 'Taittiriya Upanishad', relevance: 'Respect your father who enables your NEET preparation.' },
  { quote: 'अतिथि देवो भव', translation: 'Let the guest be your god', source: 'Taittiriya Upanishad', relevance: 'Treat every patient as divine when you become a doctor.' },
  { quote: 'यत्र नार्यस्तु पूज्यन्ते रमन्ते तत्र देवताः', translation: 'Where women are honored, there the gods are pleased', source: 'Manusmriti', relevance: 'As a woman pursuing medicine, you embody divine strength and wisdom.' },
  { quote: 'सर्वे भवन्तु सुखिनः सर्वे सन्तु निरामयाः', translation: 'May all be happy, may all be free from illness', source: 'Sanskrit Prayer', relevance: 'This is your future mission as a doctor - universal health and happiness.' },
  { quote: 'लोकाः समस्ताः सुखिनो भवन्तु', translation: 'May all worlds be happy', source: 'Sanskrit Prayer', relevance: 'Your medical service will contribute to universal well-being.' },
  { quote: 'कृण्वन्तो विश्वमार्यम्', translation: 'Making the whole world noble', source: 'Rigveda', relevance: 'Through medicine, you will make the world more noble and healthy.' },
  { quote: 'एकं सत् विप्रा बहुधा वदन्ति', translation: 'Truth is one, the wise call it by many names', source: 'Rigveda', relevance: 'Medical science is one truth expressed through various specializations.' },
  { quote: 'आनो भद्राः क्रतवो यन्तु विश्वतः', translation: 'Let noble thoughts come to us from every side', source: 'Rigveda', relevance: 'Be open to learning from all sources in your NEET preparation.' },
  { quote: 'वयं राष्ट्रे जाग्रयाम पुरोहिताः', translation: 'We shall be wakeful guardians of the nation', source: 'Rigveda', relevance: 'As a doctor, you will be a guardian of national health.' },
  { quote: 'धर्मो रक्षति रक्षितः', translation: 'Dharma protects those who protect it', source: 'Mahabharata', relevance: 'Your dedication to studies (dharma) will protect and reward you.' },
  { quote: 'अप्रमादो अमृतपदम्', translation: 'Vigilance is the path to immortality', source: 'Dhammapada', relevance: 'Stay vigilant and focused in your NEET preparation for lasting success.' },
  { quote: 'श्रमेण सर्वं भवति', translation: 'Everything is achieved through effort', source: 'Sanskrit Proverb', relevance: 'Your consistent effort in studies will bring NEET success.' },
  { quote: 'विद्या धनं सर्व धनं प्रधानम्', translation: 'Knowledge is the supreme wealth', source: 'Chanakya Niti', relevance: 'Medical knowledge is the greatest treasure you can acquire.' },
  { quote: 'कालः पचति भूतानि कालः संहरते प्रजाः', translation: 'Time ripens all beings, time destroys all creatures', source: 'Mahabharata', relevance: 'Use your time wisely for NEET preparation; time is precious.' },
  { quote: 'अहं ब्रह्मास्मि', translation: 'I am Brahman', source: 'Brihadaranyaka Upanishad', relevance: 'Recognize your divine potential to heal and serve humanity.' },
  { quote: 'तत्त्वमसि', translation: 'Thou art That', source: 'Chandogya Upanishad', relevance: 'You have the divine essence needed to become a great doctor.' },
  { quote: 'सो अहम्', translation: 'I am That', source: 'Isha Upanishad', relevance: 'You are one with the universal healing energy.' },
  { quote: 'अयमात्मा ब्रह्म', translation: 'This Self is Brahman', source: 'Mandukya Upanishad', relevance: 'Your true self has unlimited potential for medical excellence.' },
  { quote: 'सर्वं खल्विदं ब्रह्म', translation: 'All this is indeed Brahman', source: 'Chandogya Upanishad', relevance: 'See the divine in all your studies and future patients.' },
  { quote: 'ईशावास्यमिदं सर्वम्', translation: 'All this is pervaded by the Lord', source: 'Isha Upanishad', relevance: 'Approach your medical studies with reverence for the divine.' },
  { quote: 'यो वै भूमा तत्सुखम्', translation: 'That which is infinite is happiness', source: 'Chandogya Upanishad', relevance: 'Find infinite joy in the vast field of medical knowledge.' },
  { quote: 'सत्यं ज्ञानमनन्तं ब्रह्म', translation: 'Brahman is truth, knowledge, and infinity', source: 'Taittiriya Upanishad', relevance: 'Seek truth and infinite knowledge in your medical studies.' },
  { quote: 'रसो वै सः', translation: 'He is indeed the essence', source: 'Taittiriya Upanishad', relevance: 'Find the essence and joy in your NEET preparation.' },
  { quote: 'आनन्दो ब्रह्म', translation: 'Bliss is Brahman', source: 'Taittiriya Upanishad', relevance: 'Experience bliss in learning and serving through medicine.' },
  { quote: 'प्रज्ञानं ब्रह्म', translation: 'Consciousness is Brahman', source: 'Aitareya Upanishad', relevance: 'Develop higher consciousness through dedicated study.' },
  { quote: 'एकोऽहं बहुस्याम्', translation: 'I am one, let me become many', source: 'Chandogya Upanishad', relevance: 'Through your medical practice, multiply your healing presence.' },
  { quote: 'शान्तिः शान्तिः शान्तिः', translation: 'Peace, peace, peace', source: 'Upanishads', relevance: 'Maintain inner peace during intense NEET preparation.' },
  { quote: 'ॐ गं गणपतये नमः', translation: 'Om, salutations to Ganesha', source: 'Ganapati Mantra', relevance: 'Invoke Ganesha to remove obstacles in your NEET journey.' },
  { quote: 'ॐ नमः शिवाय', translation: 'Om, salutations to Shiva', source: 'Panchakshara Mantra', relevance: 'Seek Shiva\'s blessings for transformation through knowledge.' },
  { quote: 'ॐ नमो भगवते वासुदेवाय', translation: 'Om, salutations to Lord Vasudeva', source: 'Dwadashakshara Mantra', relevance: 'Surrender to divine will while preparing for NEET.' },
  { quote: 'हरे राम हरे राम राम राम हरे हरे', translation: 'Hare Rama Hare Rama Rama Rama Hare Hare', source: 'Maha Mantra', relevance: 'Chant for mental clarity and focus during studies.' },
  { quote: 'गायत्री मन्त्र', translation: 'Om Bhur Bhuvaḥ Swaḥ', source: 'Rigveda', relevance: 'Invoke divine light to illuminate your path to medical success.' },
  { quote: 'मृत्युञ्जय मन्त्र', translation: 'Om Tryambakam Yajamahe', source: 'Rigveda', relevance: 'Seek protection and healing energy for your medical journey.' },
  { quote: 'महामृत्युञ्जय मन्त्र', translation: 'We worship the three-eyed one', source: 'Rigveda', relevance: 'Develop the third eye of wisdom for medical diagnosis.' }
];