export const hinduWisdom = [
  { quote: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन', translation: 'You have the right to perform your actions, but not to the fruits of action', source: 'Bhagavad Gita 2.47', relevance: 'Focus on studying without attachment to results. Your dedication to NEET preparation is your dharma.' },
  { quote: 'श्रद्धावान् लभते ज्ञानं तत्परः संयतेन्द्रियः', translation: 'The faithful one, devoted to knowledge and controlling the senses, attains wisdom', source: 'Bhagavad Gita 4.39', relevance: 'Faith in your abilities and controlled focus on studies will lead you to medical knowledge and NEET success.' },
  { quote: 'उद्यमेन हि सिध्यन्ति कार्याणि न मनोरथैः', translation: 'Success comes through effort, not through wishful thinking', source: 'Hitopadesh', relevance: 'NEET success requires consistent daily effort in solving questions and studying, not just dreaming about becoming a doctor.' },
  { quote: 'विद्या ददाति विनयं विनयाद्याति पात्रताम्', translation: 'Knowledge gives humility, from humility comes worthiness', source: 'Hitopadesh', relevance: 'As you gain medical knowledge through NEET preparation, stay humble and worthy of serving patients as a future doctor.' },
  { quote: 'सत्यमेव जयते नानृतं', translation: 'Truth alone triumphs, not falsehood', source: 'Mundaka Upanishad', relevance: 'Be truthful in your preparation - honestly assess your weaknesses and work on them. Truth in self-evaluation leads to NEET success.' },
  { quote: 'आत्मानं विद्धि', translation: 'Know thyself', source: 'Upanishads', relevance: 'Understand your learning style, peak study hours, and strengths. Self-knowledge is key to optimizing your NEET preparation strategy.' },
  { quote: 'धैर्यं सर्वत्र साधनम्', translation: 'Patience is the means to everything', source: 'Sanskrit Proverb', relevance: 'NEET preparation is a long journey. Maintain patience with difficult concepts and trust the process of gradual improvement.' },
  { quote: 'योगः कर्मसु कौशलम्', translation: 'Yoga is skill in action', source: 'Bhagavad Gita 2.50', relevance: 'Develop skillful study techniques and efficient problem-solving methods for NEET preparation.' },
  { quote: 'न हि ज्ञानेन सदृशं पवित्रमिह विद्यते', translation: 'Nothing in this world is as purifying as knowledge', source: 'Bhagavad Gita 4.38', relevance: 'Medical knowledge you gain through NEET preparation will purify your mind and help you serve humanity.' },
  { quote: 'तत्त्वं पुष्पं फलं तोयं यो मे भक्त्या प्रयच्छति', translation: 'Whoever offers Me with devotion a leaf, flower, fruit or water, I accept it', source: 'Bhagavad Gita 9.26', relevance: 'Offer your studies as devotion. Every question solved with dedication is an offering to the divine.' },
  { quote: 'अभ्यासेन तु कौन्तेय वैराग्येण च गृह्यते', translation: 'Through practice and detachment, it can be controlled', source: 'Bhagavad Gita 6.35', relevance: 'Control your mind through consistent practice of studying and detachment from distractions.' },
  { quote: 'श्रेयान्स्वधर्मो विगुणः परधर्मात्स्वनुष्ठितात्', translation: 'Better is one\'s own dharma, though imperfectly performed, than the dharma of another well performed', source: 'Bhagavad Gita 3.35', relevance: 'Focus on your own NEET preparation journey rather than comparing with others.' },
  { quote: 'मन एव मनुष्याणां कारणं बन्धमोक्षयोः', translation: 'Mind alone is the cause of bondage and liberation for humans', source: 'Amritabindu Upanishad', relevance: 'Train your mind for NEET success. A disciplined mind leads to liberation from failure.' },
  { quote: 'यदा यदा हि धर्मस्य ग्लानिर्भवति भारत', translation: 'Whenever there is decline in righteousness, O Bharata', source: 'Bhagavad Gita 4.7', relevance: 'When you feel demotivated in studies, remember your dharma as a future doctor to serve humanity.' },
  { quote: 'कर्मयोगो विशिष्यते', translation: 'Karma Yoga is superior', source: 'Bhagavad Gita 5.2', relevance: 'Action-oriented study approach is superior to mere theoretical knowledge for NEET success.' },
  { quote: 'सर्वधर्मान्परित्यज्य मामेकं शरणं व्रज', translation: 'Abandoning all duties, take refuge in Me alone', source: 'Bhagavad Gita 18.66', relevance: 'When overwhelmed with NEET preparation, surrender your worries and trust in divine guidance.' },
  { quote: 'यत्र योगेश्वरः कृष्णो यत्र पार्थो धनुर्धरः', translation: 'Where there is Krishna, the master of yoga, and Arjuna, the archer', source: 'Bhagavad Gita 18.78', relevance: 'Where there is dedication (Krishna) and focused effort (Arjuna), there is victory in NEET.' },
  { quote: 'अहं सर्वस्य प्रभवो मत्तः सर्वं प्रवर्तते', translation: 'I am the source of all; everything emanates from Me', source: 'Bhagavad Gita 10.8', relevance: 'All knowledge, including medical science, comes from the divine source. Study with reverence.' },
  { quote: 'मत्तः परतरं नान्यत्किञ्चिदस्ति धनञ्जय', translation: 'There is nothing higher than Me, O Arjuna', source: 'Bhagavad Gita 7.7', relevance: 'Keep the highest goal in mind - serving the divine through medical practice after NEET success.' }
];

// Additional 240+ quotes will be added in subsequent updates